name: thermorawfileparser
description: Convert RAW file to mzML files
keywords:
    - raw
    - mzML
    - OpenMS
tools:
    - thermorawfileparser:
          description: |
              ThermoRawFileParser converts Thermo RAW files to open standard formats like mzML, producing indexed output files.
          homepage: https://github.com/compomics/ThermoRawFileParser
          documentation: https://github.com/compomics/ThermoRawFileParser
input:
    - meta:
          type: map
          description: |
              Groovy Map containing sample information
    - rawfile:
          type: file
          description: |
              thermo RAW file
          pattern: "*.{raw,RAW}"
output:
    - meta:
          type: map
          description: |
              Groovy Map containing sample information
              e.g. [ id:'sample1', mzml_id:'UPS1_50amol_R3' ]
    - mzmls_converted:
          type: file
          description: indexed mzML files
          pattern: "*.mzML"
    - log:
          type: file
          description: log file
          pattern: "*.log"
    - versions:
          type: file
          description: File containing software version
          pattern: "versions.yml"
authors:
    - "@daichengxin"
    - "@ypriverol"
